export const lightTheme = {
    backgroundColor: '#ededed', 
    textColor: '#000', 
    buttonColor: '#FC2247', 
    buttonTextColor: '#fff', 
    calendarBackground: '#fff', 
    quoteContainerBackground: '#fff', 
    quoteTextColor: '#333', 
    subtitleTextColor: '#555', 
    workoutBoxColor: '#F0F0F0', 
    workoutTextColor: '#000',   
    calendarTheme: {
      selectedDayBackgroundColor: '#00adf5',
      todayTextColor: '#00adf5',
      dayTextColor: '#2d4150',
      arrowColor: 'orange',
      monthTextColor: 'black',
      textDayFontWeight: '300',
      textMonthFontWeight: 'bold',
      textDayHeaderFontWeight: '500',
    },
    trackerButtonBackground: '#fff', 
    trackerButtonTextColor: '#000', 
    viewWorkoutsButtonBackground: '#fff', 
    viewWorkoutsButtonTextColor: '#000', 
  };
  
  export const darkTheme = {
    backgroundColor: '#000', 
    textColor: '#fff', 
    buttonColor: '#FC2247', 
    buttonTextColor: '#fff', 
    calendarBackground: '#505050', 
    quoteContainerBackground: '#505050', 
    quoteTextColor: '#fff', 
    subtitleTextColor: '#aaa', 
    workoutBoxColor: '#333333', 
    workoutTextColor: '#fff',  
    calendarTheme: {
      backgroundColor: '#505050',
      selectedDayBackgroundColor: '#4d4d4d',
      todayTextColor: '#fff',
      dayTextColor: '#fff',
      arrowColor: '#888',
      monthTextColor: '#fff',
      textDayFontWeight: '300',
      textMonthFontWeight: 'bold',
      textDayHeaderFontWeight: '500',
    },
    trackerButtonBackground: '#505050', 
    trackerButtonTextColor: '#fff', 
    viewWorkoutsButtonBackground: '#505050', 
    viewWorkoutsButtonTextColor: '#fff',
  };
  